import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import '../assets/scss/main.scss';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Content from "@/components/Content";
import { headers } from 'next/headers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = headers().get('x-pathname');
  const isHome = pathname === 'home'
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {isHome ? children : <Content>{children}</Content>}
        <Footer />
      </body>
    </html>
  );
}
